export const SET_AUTH = "SET_AUTH";

export const SET_ERROR = "SET_ERROR";

export const SET_CURRENT_EQUIPMENT = "SET_CURRENT_EQUIPMENT";
export const SET_CURRENT_STYLES = "SET_CURRENT_STYLES";
export const SET_CURRENT_AVAILTIMES = "SET_CURRENT_AVAILTIMES";
export const SET_FIELD_ERRORS = "SET_FIELD_ERRORS";