version: '3.5'
services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/front
      - /usr/src/front/node_modules
      - /usr/src/front/build
    ports:
      - '80:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_ACCESS_KEY_ID=${REACT_APP_ACCESS_KEY_ID}
      - REACT_APP_ACCESS_SECRET_KEY=${REACT_APP_ACCESS_SECRET_KEY}
      - REACT_APP_OMISE_PUBLIC_KEY=${REACT_APP_OMISE_PUBLIC_KEY}
      - REACT_APP_OMISE_SECRET_KEY=${REACT_APP_OMISE_SECRET_KEY}
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=oldman
      - MYSQL_PASSWORD=43654
      - MYSQL_ROOT_PASSWORD=1834
  back:
    container_name: backend
    build: ./backend
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/backend
    ports:
      - "8000:8000"
    depends_on:
      - db