# Generated by Django 3.1.4 on 2020-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0002_photographer_style'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuserprofile')),
                ('fav_photographers', models.ManyToManyField(blank=True, null=True, related_name='fav_photographers', to='photographers.Photographer')),
            ],
        ),
    ]
