# Generated by Django 3.1.4 on 2020-12-01 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('reviewJob', models.OneToOneField(limit_choices_to={'JobStatus': 'Closed'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jobs.jobinfo')),
                ('reviewDetail', models.TextField(blank=True, null=True)),
                ('rateJob', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
