# Generated by Django 3.1.4 on 2020-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_actor', to='users.customuserprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='noti_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_receiver', to='users.customuserprofile'),
        ),
    ]
