# Generated by Django 3.1.4 on 2020-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('REMAINING', 'Remaining')], max_length=10)),
                ('payment_amount', models.FloatField()),
            ],
        ),
    ]
