# Generated by Django 3.1.4 on 2020-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('photographers', '0002_photographer_style'),
        ('jobs', '0003_auto_20201201_2114'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_for_job', to='jobs.jobinfo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_photographer', to='photographers.photographer'),
        ),
    ]
