# Generated by Django 3.1.4 on 2020-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreservation',
            name='job_avail_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_avail_time', to='photographers.availtime'),
        ),
    ]
