# Generated by Django 3.1.4 on 2020-12-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_jobreservation_job_avail_time'),
        ('photographers', '0002_photographer_style'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='job_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_customer', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_of_photographer', to='photographers.photographer'),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='job_reservation',
            field=models.ManyToManyField(null=True, to='jobs.JobReservation'),
        ),
    ]
